const DB_NAME="FitFlowDB",DB_VERSION=1;
let db;
const stores=[["members",{keyPath:"id",autoIncrement:true}],["attendance",{keyPath:"id",autoIncrement:true}],["payments",{keyPath:"id",autoIncrement:true}],["trainers",{keyPath:"id",autoIncrement:true}]];
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=e=>{const d=e.target.result;stores.forEach(([n,o])=>{if(!d.objectStoreNames.contains(n))d.createObjectStore(n,o)})};r.onsuccess=e=>{db=e.target.result;resolve()};r.onerror=()=>reject(r.error)})}
function all(n){return new Promise((res,rej)=>{const r=db.transaction(n).objectStore(n).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function add(n,d){return new Promise((res,rej)=>{const r=db.transaction(n,"readwrite").objectStore(n).add(d);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function del(n,id){return new Promise((res,rej)=>{const r=db.transaction(n,"readwrite").objectStore(n).delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function renderMembers(){all("members").then(a=>{document.getElementById("memberRows").innerHTML=a.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.mobile)}</td><td>${esc(r.plan)}</td><td>${esc(r.expiry)}</td><td>${esc(r.trainer)}</td><td>${esc(r.goal)}</td><td><button class="delete" onclick="removeRecord('members',${r.id})">Delete</button></td></tr>`).join("")||`<tr><td colspan="7">No members yet.</td></tr>`;document.getElementById("heroMembers").textContent=a.length})}
function renderAttendance(){all("attendance").then(a=>{a.sort((x,y)=>(y.date+y.time).localeCompare(x.date+x.time));document.getElementById("attendanceRows").innerHTML=a.map(r=>`<tr><td>${esc(r.member)}</td><td>${esc(r.date)}</td><td>${esc(r.time)}</td><td>${esc(r.trainer)}</td><td><button class="delete" onclick="removeRecord('attendance',${r.id})">Delete</button></td></tr>`).join("")||`<tr><td colspan="5">No attendance records yet.</td></tr>`})}
function renderPayments(){all("payments").then(a=>{document.getElementById("paymentRows").innerHTML=a.map(r=>`<tr><td>${esc(r.receipt)}</td><td>${esc(r.member)}</td><td>₹${Number(r.amount).toFixed(2)}</td><td>${esc(r.date)}</td><td>${esc(r.status)}</td><td>${esc(r.method)}</td><td><button class="delete" onclick="removeRecord('payments',${r.id})">Delete</button></td></tr>`).join("")||`<tr><td colspan="7">No payments yet.</td></tr>`})}
function renderTrainers(){all("trainers").then(a=>{document.getElementById("trainerRows").innerHTML=a.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.specialization)}</td><td>${esc(r.member)}</td><td>${esc(r.workout)}</td><td><button class="delete" onclick="removeRecord('trainers',${r.id})">Delete</button></td></tr>`).join("")||`<tr><td colspan="5">No trainer programs yet.</td></tr>`})}
window.removeRecord=async(n,id)=>{if(confirm("Delete this record?")){await del(n,id);renderAll()}}
function renderAll(){renderMembers();renderAttendance();renderPayments();renderTrainers()}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab,.panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.tab).classList.add("active")});
memberForm.onsubmit=async e=>{e.preventDefault();await add("members",{name:mName.value,mobile:mMobile.value,email:mEmail.value,plan:mPlan.value,start:mStart.value,expiry:mExpiry.value,trainer:mTrainer.value,goal:mGoal.value});e.target.reset();renderMembers();alert("Member saved.")};
attendanceForm.onsubmit=async e=>{e.preventDefault();await add("attendance",{member:aMember.value,date:aDate.value,time:aTime.value,trainer:aTrainer.value});e.target.reset();renderAttendance();alert("Attendance saved.")};
paymentForm.onsubmit=async e=>{e.preventDefault();await add("payments",{member:pMember.value,receipt:pReceipt.value,amount:pAmount.value,date:pDate.value,status:pStatus.value,method:pMethod.value,notes:pNotes.value});e.target.reset();renderPayments();alert("Payment saved.")};
trainerForm.onsubmit=async e=>{e.preventDefault();await add("trainers",{name:tName.value,specialization:tSpecialization.value,member:tMember.value,workout:tWorkout.value});e.target.reset();renderTrainers();alert("Trainer program saved.")};
openDB().then(renderAll).catch(()=>{dbStatus.textContent="Database unavailable";dbStatus.style.background="#fff0f0";dbStatus.style.color="#c44141"});
